### ISSUE TITLE
yubikey 2-factor auth challenge-response for OSX login and screensaver 

### ISSUE THREAD

**Issue by klali** [Yubico/yubico-pam#24]
original issue: http://code.google.com/p/yubico-pam/issues/detail?id=54

What steps will reproduce the problem?
1. Installed yubico-pam
2. Followed steps outlined to configure PAM here: https://github.com/Yubico/yubico-pam/wiki/ChallengeResponse-(on-Mac-OS-X)
3. lot and lots and lots of google

What is the expected output? What do you see instead?

Expected to be able to use yubikey challenge-response in addition to my password (2 factor auth) for both my OSX login and returning from screensave, also for sudo access. 

Sudo PAM works great
OSX login and screensaver I can't get working.

What version of the product are you using? On what operating system?
OSX 10.8.4
yubico-pam 2.13

**Comment by face** [comment]
Info for Mojave:   I could not get `/usr/local/lib/security/pam_yubico.so` to work.    Turns out the download on yubico.com's website does not work with Mojave.   The solution was to use homebrew:

1. Uninstall with their script https://support.yubico.com/support/solutions/articles/15000012625-uninstalling-the-macos-login-tool
2. `brew install yubico-pam`

After I switch to the pam_yubico.so from homebrew, everything else worked as documented.
